name: lint2
on: [push]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - run: npm install
        working-directory: ./docs-web/src/main/webapp
      - run: npx eslint ".docs-web/src/main/webapp/**/*.js"
        working-directory: ./docs-web/src/main/webapp 