name: Grunt build to run retire

on: [push]

jobs:
  grunt-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12

    - name: install and run grunt
      working-directory: ./docs-web/src/main/webapp/
      run: | 
        npm install
        grunt retire