name: Grunt build to run retire

on: [push]

jobs:
  grunt-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12

    - name: Compile with Grunt
      uses: elstudio/actions-js-build/build@v4
      with:
        wdPath: './docs-web/src/main/webapp/'